[package]
name = "fdpi"
version = "0.1.0"
edition = "2021"

[lib]
name = "fdpi"
path = "src/lib.rs"

[dependencies]
pnet = "0.35.0"
prost = "0.13.3"
phf = { version = "0.11", features = ["macros"] }
log = "0.4.22"

[build-dependencies]
prost-build = "0.13.3"
